LICENSE.md

Added MIT license file.
closes #3

chore(license): added MIT license file

---

README.md

Updated readme.md with links and instructions.
Removed unnecessary NX generared readme

chore: updated readme for stackblitz demo

---

CONTRIBUTING.md
README.md

Added CONTRIBUTING.md
closes #19

chore: added contributing guide

---

.github/PULL_REQUEST_TEMPLATE.md

**Description:**
Updated PR template to have checkboxes
**Related issue (if exists):**
fixes #41

chore: updated PR template

---

.github/workflows/ci.yml

fix: workflow name for badges

---

libs/ng-utils/src/lib/use-http-image-source/use-http-image-source.pipe.spec.ts
libs/ng-utils/src/lib/use-http-image-source/use-http-image-source.pipe.ts

revoke Object URL when pipe is destroyed
revoke Object URL when new Object URL is created
show loading image again when image url is changed
resolves #56

fix: revoke Object URL

---

.stackblitzrc
README.md
angular.json
nx.json

chore: update stackblitz integration

---

libs/cypress-indexeddb/README.md
libs/cypress-indexeddb/package.json
package-lock.json
package.json

Fix: Updated documentation, and the dev dependencies to make sure the library can be built.
fixes #74

fix: fixed documentation issues

---

libs/ng-utils/README.md
libs/ng-utils/package.json
libs/route-config/README.md
libs/route-config/package.json

Updated the route-config and ng-utils documentation to use `yarn add`
fixes #73

fix: documentation fixes for ng-utils and route-config

---

apps/showcase/src/app/modules/rxidb-showcase/components/rxidb-auto-increment/rxidb-auto-increment.component.ts
apps/showcase/src/app/modules/rxidb-showcase/components/rxidb-key-value-pair-showcase/rxidb-key-value-pair-showcase.component.ts

chore: upgraded to typed forms

---

libs/cypress-indexeddb/README.md
libs/cypress-indexeddb/package.json
libs/cypress-indexeddb/src/lib/create-object-store.ts
libs/cypress-indexeddb/src/lib/delete-database.ts
libs/cypress-indexeddb/src/lib/helpers.ts
libs/cypress-indexeddb/src/lib/object-store-CRUD.ts
libs/cypress-indexeddb/src/lib/object-store-metadata.ts
libs/cypress-indexeddb/src/lib/open-database.ts
libs/cypress-indexeddb/src/lib/upgrade-database.ts
libs/ng-utils/README.md
libs/ng-utils/package.json
libs/ng-utils/src/lib/use-http-image-source/use-http-image-source-pipe.module.ts
libs/ng-utils/src/lib/use-http-image-source/use-http-image-source.injector.ts
libs/ng-utils/src/lib/use-http-image-source/use-http-image-source.pipe.ts
libs/route-config/README.md
libs/route-config/package.json
libs/route-config/src/lib/route-config.module.ts
libs/route-config/src/lib/route-config.service.ts
libs/route-config/src/lib/route-data-has/route-data-has.directive.ts
libs/route-config/src/lib/route-data/route-data.directive.ts
libs/route-config/src/lib/route-tag/not-in-route-tags.pipe.ts
libs/route-config/src/lib/route-tag/route-tag.directive.ts

chore: update existing libraries with tsdoc documentation

---

package-lock.json
package.json

chore: upgrade cypress

---

libs/ng-utils/package.json
libs/route-config/package.json

This change updates the package.json files for the angular packages to allow support for v14
Closes #116

chore: update peerDependencies for libraries

---

libs/vue-route-guard/README.md
libs/vue-route-guard/src/lib/types.ts

Added documentation to the readme

chore: added documentation to the readme

---

.github/workflows/release.yml

chore: prepare protected branch release workflow

---

.github/workflows/release.yml
libs/vue-route-guard/project.json

added vue route guard to release workflow
closes  #114

chore: added vue route guard to release workflow

---

libs/vue-route-guard/package.json
libs/vue-route-guard/tsconfig.json
libs/vue-route-guard/vite.config.ts
package-lock.json
package.json

feat: add ts types to build

---

HOW_TO_RELEASE.md

A small fix to correct the target name to add to the targets property
_(added through GitHub web ui)_

docs(release): ✏️ tiny update to HOW_TO_RELEASE.md

---

libs/cypress-indexeddb/README.md
libs/cypress-indexeddb/package.json

In this PR:
- updated peer dependencies for the v1.4.0 package
- updated documentation with which version to use
- removed part of the documentation that is no longer necessary.

chore: prepare cypress-indexeddb 1.4.0 release

---

libs/cypress-indexeddb/package.json

fixes 163 after published to npm

fix: peer dependency

---

libs/ng-utils/package.json
libs/route-config/package.json

Angular requirements were still set to < 16. Updated the `package.json` of the Angular libs to allow for Angular 16.
Fixes #172

fix: update angular requirements to allow angular 16
